### ISSUE TITLE
cudahash: Completely failed to build Cuda error in file 

### ISSUE THREAD

**Issue by ZaiwangLi** [poodarchu/Det3D#48]
During training, I meet the problem below
at epoch 63 with --nproc_per_node=2, samples_per_gpu=6 and workers_per_gpu=6
at epoch 81 with --nproc_per_node=2, samples_per_gpu=4 and workers_per_gpu=4

cudahash: Completely failed to build
Cuda error in file '/root/spconv/src/cuhash/hash_table.cpp' in line 194 : an illegal memory access was encountered.

**Comment by poodarchu** [comment]
Please use template

**Comment by peiyunh** [comment]
I suspect you might be using spconv-1.1. In that case, you need to add `use_hash=False` as an additional argument every time you instantiate a sparse convolution operation (or sub-manifold sparse convolution) in `scn.py`. An easier way out is to follow instructions in `INSTALL.md` and checkout a specific branch.

**Comment by ZaiwangLi** [comment]
@peiyunh Thanks for apply.
Hey guys, I haven't try @peiyunh suggestion.

I solved this problem by this answer:
[https://github.com/traveller59/spconv/issues/74]

**Comment by poodarchu** [comment]
> @peiyunh Thanks for reply.
> Hey guys, I haven't try @peiyunh suggestion.
> 
> I solved this problem by this answer:
> [https://github.com/[traveller59/spconv/issues/74](https://github.com/traveller59/spconv/issues/74)]

I suggest you use my version of spconv.
