### ISSUE TITLE
Invalid device ordinal

### ISSUE THREAD

**Issue by Gang-Chen-China** [poodarchu/Det3D#86]
Hi, i was training the Pointpillars on Nuscenes, but it shows cuda runtime error: invalid device ordinal，does anyone know how to solve it?

**Comment by Gang-Chen-China** [comment]
thanks，i have solved it !!!

**Comment by turboxin** [comment]
hi @Gang-Chen-China,  could you please share your solution to this problem, thanks a lot~

**Comment by Gang-Chen-China** [comment]
> hi @Gang-Chen-China, could you please share your solution to this problem, thanks a lot~

yeah , i train with single GPU and change the train.sh . kile this:
python3  ./tools/train.py ./examples/point_pillars/configs/original_pp_mghead_syncbn_kitti.py --work_dir=$PP_WORK_DIR
